name: Auto Deploy Update Set to Demo 2

on:
  push:
    paths:
      - 'updates/*.xml'  

jobs:
  deploy-update-set:
    name: Deploy to ServiceNow Demo 2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Identify pushed update set file
        id: find_file
        run: |
          FILE=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'updatesets/' | head -n 1)
          echo "file_path=$FILE" >> $GITHUB_ENV

      - name: Display selected file
        run: echo "File to deploy:$file_path"
        env:
          file_path: ${{ env.file_path }}


      - name: Deploy update set to Demo 2
        env:
          SN_INSTANCE: agreeyasolutionsincdemo2.service-now.com 
          SN_USER: ${{ secrets.SN_DEMO2_USER }}
          SN_PASS: ${{ secrets.SN_DEMO2_PASS }}
        run: |
          FILE="${{ steps.find_file.outputs.file_path }}"
          if [ -z "$FILE" ]; then
            echo "No update set file found in commit."
            exit 1
          fi

          echo "Importing update set: $FILE to $SN_INSTANCE"

          curl -s -w "\nHTTP STATUS: %{http_code}\n" -o response.txt \
            -u "$SN_USER:$SN_PASS" \
            -X POST "https://$SN_INSTANCE/api/now/import/sys_update_xml" \
            -H "Accept: application/json" \
            -H "Content-Type: application/xml" \
            --data-binary @"$FILE"

          cat response.txt
