name: Deploy Update Set to Demo 2

on:
  push:
    branches:
      - main
    paths:
      - 'updates/**.xml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Find latest update set file
        id: find_file
        run: |
          FILE=$(find updatesets -type f -name "*.xml" | sort | tail -n 1)
          echo "file_path=$FILE" >> $GITHUB_OUTPUT

      - name: Display selected file
        run: echo "File to deploy:${{ steps.find_file.outputs.file_path }}"

      - name: Deploy update set to Demo 2
        env:
          SN_INSTANCE: agreeyasolutionsincdemo2.service-now.com
          SN_USER: ${{ secrets.SN_DEMO2_USER }}
          SN_PASS: ${{ secrets.SN_DEMO2_PASS }}
        run: |
          FILE="${{ steps.find_file.outputs.file_path }}"
          if [ -z "$FILE" ]; then
            echo "No update set file found."
            exit 1
          fi

          echo "Importing update set: $FILE to $SN_INSTANCE"

          curl -s -w "\nHTTP STATUS: %{http_code}\n" -o response.txt \
            -u "$SN_USER:$SN_PASS" \
            -X POST "https://$SN_INSTANCE/api/now/import/sys_update_xml" \
            -H "Accept: application/json" \
            -H "Content-Type: application/xml" \
            --data-binary @"$FILE"

          cat response.txt
