name: Deploy Update Set to Demo 3

on:
  push:
    branches:
      - main
    paths:
      - 'updates/**/*.xml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Find latest update set file
        id: find_file
        run: |
          echo "Looking for update set XML files in updates/ folder..."
          FILE=$(find updates -type f -name "*.xml" | sort | tail -n 1)
          echo "Found update set file: $FILE"
          echo "file_path=$FILE" >> $GITHUB_ENV

      - name: Display selected file
        run: |
          echo "File to deploy: $file_path"

      - name: Deploy update set to Demo 3
        env:
          SN_INSTANCE: agreeyasolutionsincdemo3.service-now.com
          SN_USER: ${{ secrets.SN_DEMO3_USER }}
          SN_PASS: ${{ secrets.SN_DEMO3_PASS }}
          file_path: ${{ env.file_path }}
        run: |
          if [ -z "$file_path" ]; then
            echo "No update set file found."
            exit 1
          fi
          echo "Importing update set: $file_path to $SN_INSTANCE"

          curl -s -w "\nHTTP STATUS: %{http_code}\n" -o response.txt \
            -u "$SN_USER:$SN_PASS" \
            -X POST "https://$SN_INSTANCE/api/ays/updatesetimporterapi/import?file_name=$(basename $file_path)" \
            -H "Accept: application/json" \
            -H "Content-Type: application/xml" \
            --data-binary @"$file_path"

          cat response.txt
